version: '3.7'
services:
    postgres:
        image: postgres:10.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d/
    airflow:
        build:
            context: ./build
            dockerfile: Dockerfile-airflow
            args:
                AIRFLOW_DEPS: s3
        restart: always
        depends_on:
            - postgres
        env_file:
            - airflow.env
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://airflow:airflow@postgres:5432/sample
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
